/****************************************************************************/
/*                                                                          */
/*      文件名:    Resource.h                                               */
/*      创建日期:  2011年10月07日                                           */
/*      作者:      Sagasarate                                               */
/*                                                                          */
/*      本软件版权归Sagasarate(sagasarate@sina.com)所有                     */
/*      你可以将本软件用于任何商业和非商业软件开发，但                      */
/*      必须保留此版权声明                                                  */
/*                                                                          */
/****************************************************************************/
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by USOEdit.rc
//
#define ID_ADD                          3
#define ID_SHOW_FULL_MAP                3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_CONTROLPANELVIEW            103
#define IDR_MAINFRAME                   128
#define IDR_USOTYPE                     129
#define IDD_SET_PATH_LIST               130
#define IDD_IMPORT                      131
#define IDD_DIALOG_COLOR                132
#define IDD_DIALOG_FX_EDIT              133
#define IDD_SKIN_PART_SETTING           134
#define IDD_FX_SELECT                   135
#define IDD_DIALOG_WOW_M2_IMPORT        136
#define IDD_RENDER_PERFORMANCE          137
#define IDD_WOW_CHAR_SETTING            138
#define IDD_DIALOG_WOW_ITEM_IMPORT      139
#define IDD_WOW_CHAR_EQUIPMENT_SETTING  140
#define IDD_DIALOG_WMO_IMPORT           141
#define IDD_DIALOG_WOW_CHAR_IMPORT      142
#define IDD_DIALOG_CAMERA_SETTING       143
#define IDD_DIALOG_ADT_IMPORT           144
#define IDR_MENU_POPUP                  144
#define IDD_DIALOG_TEXTURE_VIEWER       145
#define IDD_DIALOG_LIGHT_SETTING        146
#define IDD_DIALOG_FILE_VIEWER          147
#define IDD_DIALOG_WOW_CREATURE_IMPORT  148
#define IDD_DIALOG_MAP_VIEW             149
#define IDD_DIALOG_ANI_SETTING          150
#define IDD_DIALOG_TRIANGLES_VIEWER     151
#define IDD_DIALOG_BONE_VIEWER          152
#define IDD_DIALOG_ANI_SEQUENCE_VIEWER  153
#define IDD_DIALOG_ANI_FRAME_VIEW       154
#define IDD_DIALOG_PARTICLE_EMITTER_PARAM_VIEWER 155
#define IDD_DIALOG_SENCE_TREE_VIEW      156
#define IDD_DIALOG_HEIGHT_TEST          157
#define IDD_DIALOG_M2_CAMERA_VIEWER     158
#define IDD_DIALOG_ATTACHMENT_VIEWER    159
#define IDD_DIALOG1                     160
#define IDD_DIALOG_M2_SKIN_VIEW         160
#define IDC_EDIT_PATH_LIST              1000
#define IDC_EDIT1                       1001
#define IDC_SELECT_FILE                 1002
#define IDC_EDIT15                      1002
#define IDC_EDIT7                       1002
#define IDC_CHECK_USE_TEXTURE_PATH      1003
#define IDC_EDIT6                       1003
#define IDC_SPACE_UNIT                  1003
#define IDC_EDIT_TEXTURE_COL            1003
#define IDC_CHECK_USE_FX_PATH           1004
#define IDC_EDIT17                      1004
#define IDC_NEAR_FACE                   1004
#define IDC_DIR_X                       1004
#define IDC_EDIT_TEXTURE_ROW            1004
#define IDC_EDIT_HEIGHT                 1004
#define IDC_EDIT2                       1005
#define IDC_FAR_FACE                    1005
#define IDC_DIR_Y                       1005
#define ROTATION                        1005
#define IDC_EDIT3                       1006
#define IDC_DIR_Z                       1006
#define IDC_SELECT_TEXTURE_PATH         1007
#define IDC_EDIT_EQUIPMENT_SHOULDER     1007
#define IDC_AMBIENT_RED                 1007
#define IDC_SELECT_FX_PATH              1008
#define IDC_EDIT_EQUIPMENT_CAPE         1008
#define IDC_AMBIENT_GREEN               1008
#define IDC_CHECK1                      1009
#define IDC_EDIT_EQUIPMENT_BUST         1009
#define IDC_AMBIENT_BLUE                1009
#define IDC_ROTATE_X                    1009
#define IDC_CHECK_USE_MODEL_PATH        1010
#define IDC_EDIT_EQUIPMENT_LEG          1010
#define IDC_DIFFUSE_RED                 1010
#define IDC_ROTATE_Y                    1010
#define IDC_EDIT_FX                     1011
#define IDC_EDIT4                       1011
#define IDC_EDIT_EQUIPMENT_SHIRT        1011
#define IDC_DIFFUSE_GREEN               1011
#define IDC_SELECT_MODEL_PATH           1012
#define IDC_EDIT_EQUIPMENT_WRIST        1012
#define IDC_DIFFUSE_BLUE                1012
#define IDC_EDIT5                       1013
#define IDC_EDIT_EQUIPMENT_ENSIGN       1013
#define IDC_SPECULAR_RED                1013
#define IDC_SELECT_SKIN_FILE            1014
#define IDC_EDIT_EQUIPMENT_LEFT_HAND    1014
#define IDC_SPECULAR_GREEN              1014
#define IDC_LIST1                       1015
#define IDC_EDIT_EQUIPMENT_RIGHT_HAND   1015
#define IDC_SPECULAR_BLUE               1015
#define IDC_LIST2                       1016
#define IDC_COMBO1                      1016
#define IDC_EDIT_EQUIPMENT_BELT         1016
#define IDC_COMBO2                      1017
#define IDC_AMBIENT_ALPHA               1017
#define IDC_COMBO_HAIR_COLOR            1018
#define IDC_DIFFUSE_ALPHA               1018
#define IDC_COMBO_WHISKER_TYPE          1019
#define IDC_SPECULAR_ALPHA              1019
#define IDC_COMBO_ANIMATION             1020
#define IDC_RANGE                       1020
#define IDC_COMBO_ATTACHMENT            1021
#define IDC_THETA                       1021
#define IDC_COMBO_FACE_TYPE             1022
#define IDC_PHI                         1022
#define IDC_BUTTON_SELECT_COLOR         1023
#define IDC_SELECT_MODEL_FILE           1023
#define IDC_FALL_OFF                    1023
#define IDC_EDIT_FRAME_RATE             1024
#define IDC_ATTENUATION0                1024
#define IDC_EDIT_FRAME_OBJECT_COUNT     1025
#define IDC_EDIT_SCALE                  1025
#define IDC_ATTENUATION1                1025
#define IDC_EDIT_SUBMESH_COUNT          1026
#define IDC_ENABLE_ATTACHMENT           1026
#define IDC_ATTENUATION2                1026
#define IDC_EDIT_FACE_COUNT             1027
#define IDC_COMBO_SKIN_COLOR            1027
#define IDC_FALL_OFF2                   1027
#define IDC_EDIT_VERTEX_COUNT           1028
#define IDC_COMBO_HAIR_TYPE             1028
#define IDC_FALL_OFF3                   1028
#define IDC_SLIDER_PLAY_SPEED           1029
#define IDC_EDIT_FRAME_RATE2            1029
#define IDC_EDIT_UPDATE_RATE            1029
#define IDC_STATIC_PLAY_SPEED           1030
#define IDC_COMBO_ITEM_CLASS            1031
#define IDC_EQUIPMENT_SETTING           1031
#define IDC_CHECK_IS_BALD               1032
#define IDC_COMBO_ITEM_HAND_TYPE        1032
#define IDC_COMBO_ITEM_SUB_CLASS        1033
#define IDC_PLAY_ANI                    1033
#define IDC_COMBO_ITEM                  1034
#define IDC_COMBO_EQUIPMENT_HEAD        1034
#define IDC_COMBO_EQUIPMENT_SHOULDER    1035
#define IDC_COMBO_EQUIPMENT_CAPE        1036
#define IDC_COMBO_EQUIPMENT_BUST        1037
#define IDC_COMBO_EQUIPMENT_LEG         1038
#define IDC_COMBO_EQUIPMENT_BOOT        1039
#define IDC_COMBO_EQUIPMENT_WRIST       1040
#define IDC_COMBO_EQUIPMENT_HAND        1041
#define IDC_COMBO_EQUIPMENT_LEFT_HAND   1042
#define IDC_COMBO_EQUIPMENT_RIGHT_HAND  1043
#define IDC_FILTER                      1044
#define IDC_EDIT_FILTER_TEXT            1045
#define IDC_COMBO_EQUIPMENT_BELT        1046
#define IDC_EDIT_EQUIPMENT_HEAD         1047
#define IDC_EDIT_EQUIPMENT_BOOT         1048
#define IDC_EDIT_EQUIPMENT_HAND         1049
#define IDC_COMBO_EQUIPMENT_SHIRT       1050
#define IDC_COMBO_EQUIPMENT_ENSIGN      1051
#define IDC_EDIT_MODEL_FILE_NAME        1051
#define IDC_RADIO_SCENE_MODE            1052
#define IDC_RADIO_OBJECT_MODE           1053
#define IDC_APPLY                       1054
#define IDC_RADIO_PROJECT_MODE_PERSPECTIVE 1055
#define IDC_COMBO_MAP                   1055
#define IDC_RADIO_PROJECT_MODE_ORTHO    1056
#define IDC_COMBO_AREA                  1056
#define IDC_CHECK_IMPORT_ALL_AREA       1057
#define IDC_APPLY2                      1057
#define IDC_SET_POS                     1057
#define IDC_STATIC_BOX                  1058
#define IDC_SELECT_AMBIENT              1060
#define IDC_SELECT_DIFFUSE              1061
#define IDC_SELECT_SPECULAR             1062
#define IDC_LIGHT_TYPE                  1064
#define IDC_POS_X                       1065
#define IDC_POS_Y                       1066
#define IDC_POS_Z                       1067
#define IDC_TREE_FILE                   1068
#define IDC_SELECT_DIR                  1069
#define IDC_SAVE_TEXTURE                1070
#define IDC_BROWSER_MPQ                 1070
#define IDC_BUTTON1                     1071
#define IDC_BUTTON_MODIFY               1071
#define IDC_BUTTON_VIEW_ANI_SEQUENCE    1071
#define IDC_BUTTON_REFRESH              1071
#define IDC_DO_TEST                     1071
#define IDC_CLOSE_PREVIEW               1071
#define IDC_USE_SCENE_LIGHT             1071
#define IDC_BUTTON_USE_SELECTED_CAMERA  1071
#define IDC_BUTTON_ENABLE_ATTACHMENT    1071
#define IDC_BUTTON_CHANGE_SKIN          1071
#define IDC_MINI_MAP                    1072
#define IDC_VIEW_EMISSION_AREA_LENGTH   1072
#define IDC_VIEW_PARAMS                 1072
#define IDC_BUTTON_RENDER_SELECTED      1072
#define IDC_BUTTON_RENDER_SELECTED2     1073
#define IDC_BUTTON_HIDE_CUT_OBJECT      1073
#define IDC_BUTTON_HIDE_CUT_OBJECT2     1074
#define IDC_BUTTON_SHOW_OBJECT_NODE     1074
#define IDC_PLAY_LOOP                   1076
#define IDC_VERTEXT_LIST                1077
#define IDC_RADIO_VERTEX_MODE           1078
#define IDC_RADIO_VERTEX_MODE2          1079
#define IDC_RADIO_TRIANGLE_MODE         1079
#define IDC_LIST_BONES                  1079
#define IDC_LIST_ANI                    1080
#define IDC_EDIT_GLOBAL_SEQUENCE_ID     1081
#define IDC_EDIT_INTERPOLATION_TYPE     1082
#define IDC_LIST_FRAME                  1083
#define IDC_EDIT_FLAG                   1085
#define IDC_COMBO_EMITTER_TYPE          1086
#define IDC_EDIT_SLOWDOWN               1087
#define IDC_COMBO_ROTATION              1088
#define IDC_TREE1                       1089
#define IDC_EDIT_POS_X                  1090
#define IDC_EDIT_POS_Z                  1091
#define IDC_EDIT_POS_Y                  1092
#define IDC_LIST_CAMERA                 1093
#define IDC_LIST_ATTACHMENTS            1094
#define IDC_LIST_SKINS                  1095
#define ID_IMPORT_SMDL                  32774
#define ID_IMPORT_SN2                   32776
#define ID_SET_TEXTURE_PATH             32779
#define ID_SET_FX_PATH                  32780
#define ID_IMPORT_SKN                   32783
#define ID_IMPORT_ACT                   32784
#define ID_IMPORT_X                     32786
#define ID_IMPORT_USO                   32788
#define ID_PLAY_ANI                     32794
#define ID_DELETE_OBJ                   32795
#define ID_CLEAR_RESOURCE               32797
#define ID_STOP_PLAY_ANI                32802
#define ID_USE_SKIN                     32806
#define ID_MOVE_OBJECT                  32810
#define ID_IMPORT_MDA                   32812
#define ID_IMPORT_MDL                   32814
#define ID_IMPORT_TEXTURE               32817
#define ID_IMPORT_FX                    32818
#define ID_32819                        32819
#define ID_ORTHO                        32820
#define ID_USE_ORTHO_MODE               32821
#define ID_32822                        32822
#define ID_IMPORT_M2                    32823
#define ID_32824                        32824
#define ID_SWITCH_VISIBLE               32825
#define ID_32828                        32828
#define ID_HIDE_ALL_SUBMESH             32829
#define ID_32830                        32830
#define ID_LOAD_BLZ_CHAR_SECTION_DATA   32831
#define ID_32832                        32832
#define ID_LOAD_BLZ_ANIMATION_DATA      32833
#define ID_32834                        32834
#define ID_32835                        32835
#define ID_32836                        32836
#define ID_CAMERA_MODE_SCENE            32837
#define ID_CAMERA_MODE_OBJECT           32838
#define ID_32839                        32839
#define ID_IMPORT_M2_CHARACTER          32840
#define ID_32841                        32841
#define ID_32842                        32842
#define ID_LOAD_BLZ_HAIR_TYPE_DATA      32843
#define ID_LOAD_BLZ_WHIS                32844
#define ID_LOAD_BLZ_WHISKER_TYPE_DATA   32845
#define ID_32846                        32846
#define ID_LOAD_BLZ_DBC                 32847
#define ID_32848                        32848
#define ID_SHOW_RANDER_PERFORMANCE      32849
#define ID_32850                        32850
#define ID_IMPORT_M2_ITEM               32851
#define ID_Menu                         32852
#define ID_IMPORT_WMO                   32853
#define ID_32854                        32854
#define ID_CAMERA_SETTING               32855
#define ID_32856                        32856
#define ID_IMPORT_ADT                   32857
#define ID_32858                        32858
#define ID_VIEW_OBJECT                  32859
#define ID_LOOK_OBJECT                  32860
#define ID_32861                        32861
#define ID_RESOURCE_STAT                32862
#define ID_32863                        32863
#define ID_SHOW_ALL_SUBMESH             32864
#define ID_VIEW_TEXTURE                 32866
#define ID_32867                        32867
#define ID_SYSTEM_LIGHT_SETTING         32868
#define ID_32869                        32869
#define ID_FILE_VIEWER                  32870
#define ID_32871                        32871
#define ID_SAVE_DEPTH_TEXTURE           32872
#define ID_32873                        32873
#define ID_M2_CREATURE                  32874
#define ID_IMPORT_M2_CREATURE           32875
#define ID_32876                        32876
#define ID_CREATE_SCENE                 32877
#define ID_32878                        32878
#define ID_SET_MPQ_FILE                 32879
#define ID_32880                        32880
#define ID_EXPORT_TO_DIR                32881
#define ID_32882                        32882
#define ID_SENCE_TREE_VIEW              32883
#define ID_32884                        32884
#define ID_IMPORT_PREVIEW_OBJECT        32885
#define ID_32886                        32886
#define ID_HEIGHT_TEST                  32887
#define ID_32888                        32888
#define ID_IMPORT_WDL                   32889

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32890
#define _APS_NEXT_CONTROL_VALUE         1096
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
