#pragma once

namespace D3DLib{

extern LPCTSTR SHARED_LIB_FX;
extern LPCTSTR SHARED_PARAM_FX;

extern LPCTSTR M2_MODEL_FX;
extern LPCTSTR WMO_MODEL_FX;
extern LPCTSTR ADT_MODEL_20_FX;
extern LPCTSTR ADT_MODEL_30_FX;
extern LPCTSTR M2_PARTICLE_FX;
extern LPCTSTR M2_RIBBON_FX;
extern LPCTSTR ADT_LIQUID_FX;
extern LPCTSTR WDL_MODEL_FX;

extern LPCTSTR DEFAULT_UI_WIN_RECT_FX_NT;
extern LPCTSTR DEFAULT_UI_WIN_RECT_FX_TF;
extern LPCTSTR DEFAULT_UI_WIN_RECT_FX;
extern LPCTSTR INVERSE_COLOR_FX;
extern LPCTSTR TEXT_RECT_FX;

extern LPCTSTR DEFAULT_BOARD_FX_NT;
extern LPCTSTR DEFAULT_LINE_FX_NT;
extern LPCTSTR DEFAULT_BOUND_FRAME_FX_NT;

}