#pragma once

#define MAX_DATA_TRANSFER_SIZE		(3500)

enum SERVER_MANAGER_MSG_TYPE
{
	SM_MSG_GET_SERVICE_INFO_LIST=100,
	SM_MSG_GET_SERVICE_INFO_LIST_RESULT,

	SM_MSG_GET_PROCESS_INFO_LIST,
	SM_MSG_GET_PROCESS_INFO_LIST_RESULT,

	SM_MSG_STARTUP_SERVICE,
	SM_MSG_STARTUP_SERVICE_RESULT,

	SM_MSG_SHUTDOWN_SERVICE,
	SM_MSG_SHUTDOWN_SERVICE_RESULT,

	SM_MSG_BROWSE_SERVICE_DIR,
	SM_MSG_BROWSE_SERVICE_DIR_RESULT,

	SM_MSG_START_DOWNLOAD_SERVICE_FILE,
	SM_MSG_START_DOWNLOAD_SERVICE_FILE_RESULT,

	SM_MSG_QUERY_DOWNLOAD_SERVICE_FILE_DATA,
	SM_MSG_QUERY_DOWNLOAD_SERVICE_FILE_DATA_RESULT,

	SM_MSG_START_UPLOAD_SERVICE_FILE,
	SM_MSG_START_UPLOAD_SERVICE_FILE_RESULT,

	SM_MSG_SEND_UPLOAD_SERVICE_FILE_DATA,
	SM_MSG_SEND_UPLOAD_SERVICE_FILE_DATA_RESULT,

	SM_MSG_CREATE_DIR,
	SM_MSG_CREATE_DIR_RESULT,

	SM_MSG_DELETE_FILE,
	SM_MSG_DELETE_FILE_RESULT,

	SM_MSG_CREATE_PROCESS,
	SM_MSG_CREATE_PROCESS_RESULT,

	SM_MSG_GET_NET_ADAPTER_INFO,
	SM_MSG_GET_NET_ADAPTER_INFO_RESULT,

	SM_MSG_EXECUTE_SCRIPT,
	SM_MSG_EXECUTE_SCRIPT_RESULT,
};

enum SST_SERVER_MANAGER_MSG_ID
{
	SSMM_MSG_TYPE_ID=1,
	SSMM_MSG_RESULT,
};

enum SST_SERVER_MANAGER_RESULT_TYPE
{
	SSMRT_SUCCEED,
	SSMRT_FAILED=-1,
};

//SM_MSG_GET_SERVICE_INFO_LIST

enum SST_GET_SERVICE_INFO_LIST_RESULT
{
	SGSILR_TOTAL_COUNT=100,
	SGSILR_START_INDEX,	
	SGSILR_SERVICE_INFO,
};

enum SST_SERVICE_INFO_LIST
{
	SSIL_NAME=1,
	SSIL_INDEX,
	SSIL_IMAGE_FILE_PATH,
	SSIL_STATUS,
	SSIL_CPU_USED,
	SSIL_MEMORY,
	SSIL_VIRTUAL_MEMORY,
	SSIL_IMAGE_FILE_TIME,
};

enum enSERVICE_STATUS
{
	SS_STOP,
	SS_RUNING,
};


//SM_MSG_GET_SERVICE_INFO_LIST_RESULT

enum SST_GET_PROCESS_INFO_LIST_RESULT
{
	SGPILR_TOTAL_COUNT=100,
	SGPILR_START_INDEX,	
	SGPILR_SERVICE_INFO,
};

//SM_MSG_STARTUP_SERVICE

enum SST_SM_MSG_STARTUP_SERVICE
{
	SSUS_SERVICE_INDEX=100,
};


//SM_MSG_SHUTDOWN_SERVICE

enum SST_SM_MSG_SHUTDOWN_SERVICE
{
	SSDS_SERVICE_INDEX=100,
};


//SM_MSG_BROWSE_SERVICE_DIR
enum SST_SM_MSG_BROWSE_SERVICE_DIR
{
	SST_SMBSD_SERVICE_INDEX=100,
	SST_SMBSD_DIRECTORY_NAME,
};

//SM_MSG_BROWSE_SERVICE_DIR_RESULT
enum SST_SM_MSG_BROWSE_SERVICE_DIR_RESULT
{
	SST_SMBSDR_SERVICE_INDEX=100,
	SST_SMBSDR_TOTAL_COUNT,
	SST_SMBSDR_LEFT_COUNT,
	SST_SMBSDR_DIRECTORY,
	SST_SMBSDR_FILE_INFO,
};

enum SST_SM_FILE_INFO
{
	SST_SMFI_FILE_NAME=1,
	SST_SMFI_FILE_ATTRIBUTE,
	SST_SMFI_FILE_SIZE,
	SST_SMFI_FILE_CREATE_TIME,
	SST_SMFI_FILE_LAST_ACCESS_TIME,
	SST_SMFI_FILE_LAST_WRITE_TIME,
	SST_SMFI_FILE_MD5,
};

enum SM_MSG_BROWSE_SERVICE_DIR_RESULT_TYPE
{	
	SSMBSD_DIRECTORY_NOT_EXIST=1,
};

//SM_MSG_START_DOWNLOAD_SERVICE_FILE
enum SST_SM_MSG_START_DOWNLOAD_SERVICE_FILE
{
	SST_SMSDSF_SERVICE_INDEX=100,
	SST_SMSDSF_FILE_PATH,	
};

//SM_MSG_START_DOWNLOAD_SERVICE_FILE_RESULT
enum SST_SM_MSG_START_DOWNLOAD_SERVICE_FILE_RESULT
{
	SST_SMSDSFR_SERVICE_INDEX=100,
	SST_SMSDSFR_FILE_PATH,
	SST_SMSDSFR_TOTAL_SIZE,
	SST_SMSDSFR_ORIGIN_TOTAL_SIZE,
	SST_SMSDSFR_PACK_PROP,
	SST_SMSDSFR_FILE_LAST_WRITE_TIME,
};

enum SM_MSG_START_DOWNLOAD_SERVICE_FILE_RESULT_TYPE
{
	SMSDSFRT_FILE_NOT_EXIST=1,
};

//SM_MSG_QUERY_DOWNLOAD_SERVICE_FILE_DATA
enum SST_SM_MSG_QUERY_DOWNLOAD_SERVICE_FILE_DATA
{
	SST_SMQDSFD_SERVICE_INDEX=100,
};

//SM_MSG_QUERY_DOWNLOAD_SERVICE_FILE_DATA_RESULT
enum SST_SM_MSG_QUERY_DOWNLOAD_SERVICE_FILE_DATA_RESULT
{
	SST_SMQDSFDR_SERVICE_INDEX=100,
	SST_SMQDSFDR_TOTAL_SIZE,
	SST_SMQDSFDR_LEFT_SIZE,	
	SST_SMQDSFDR_DATA,
};


//SM_MSG_START_UPLOAD_SERVICE_FILE
enum SST_SM_MSG_START_UPLOAD_SERVICE_FILE
{
	SST_SMSUSF_SERVICE_INDEX=100,
	SST_SMSUSF_FILE_PATH,
	SST_SMSUSF_TOTAL_SIZE,
	SST_SMSUSF_ORIGIN_TOTAL_SIZE,
	SST_SMSUSF_PACK_PROP,
	SST_SMSUSF_FILE_LAST_WRITE_TIME,
};

//SM_MSG_START_UPLOAD_SERVICE_FILE_RESULT
enum SST_SM_MSG_START_UPLOAD_SERVICE_FILE_RESULT
{	
	SST_SMSUSFR_SERVICE_INDEX=100,
	SST_SMSUSFR_FILE_PATH,	
};


//SM_MSG_SEND_UPLOAD_SERVICE_FILE_DATA
enum SST_SM_MSG_SEND_UPLOAD_SERVICE_FILE_DATA
{
	SST_SMSUSFD_SERVICE_INDEX=100,
	SST_SMSUSFD_TOTAL_SIZE,
	SST_SMSUSFD_LEFT_SIZE,	
	SST_SMSUSFD_DATA,
};

//SM_MSG_SEND_UPLOAD_SERVICE_FILE_DATA_RESULT
enum SST_SM_MSG_SEND_UPLOAD_SERVICE_FILE_DATA_RESULT
{
	SST_SMSUSFDR_SERVICE_INDEX=100,
};

//SM_MSG_CREATE_DIR
enum SST_SM_MSG_CREATE_DIR
{
	SST_SMCD_SERVICE_INDEX=100,
	SST_SMCD_DIR_NAME,
};

//SM_MSG_CREATE_DIR_RESULT
enum SST_SM_MSG_CREATE_DIR_RESULT
{
	SST_SMCDR_SERVICE_INDEX=100,
};


//SM_MSG_DELETE_FILE
enum SST_SM_MSG_DELETE_FILE
{
	SST_SMDF_SERVICE_INDEX=100,
	SST_SMDF_FILE_PATH,
};


//SM_MSG_DELETE_FILE_RESULT
enum SST_SM_MSG_DELETE_FILE_RESULT
{
	SST_SMDFR_SERVICE_INDEX=100,	
};

//SM_MSG_CREATE_PROCESS
enum SST_SM_MSG_CREATE_PROCESS
{
	SST_SMCP_SERVICE_INDEX=100,
	SST_SMCP_IMAGE_FILE_PATH,
	SST_SMCP_WORK_DIR,
	SST_SMCP_PARAM,
};

//SM_MSG_CREATE_PROCESS_RESULT
enum SST_SM_MSG_CREATE_PROCESS_RESULT
{
	SST_SMCPR_SERVICE_INDEX=100,
};

//SM_MSG_GET_NET_ADAPTER_INFO_RESULT
enum SST_SM_MSG_GET_NET_ADAPTER_INFO_RESULT
{
	SST_SMGNAIR_TOTAL_COUNT=100,
	SST_SMGNAIR_START_INDEX,		
	SST_SMGNAIR_NET_ADAPTER_INFO,
};

enum SST_NET_ADAPTER_INFO
{
	SST_NAI_INDEX=1,
	SST_NAI_IP_ADDRESS,
	SST_NAI_SEND_FLUX,
	SST_NAI_RECV_FLUX,
};

//SM_MSG_EXECUTE_SCRIPT
enum SST_SM_MSG_EXECUTE_SCRIPT
{
	SST_SMES_SERVICE_INDEX=100,
	SST_SMES_SCRIPT_TYPE,
	SST_SMES_SCRIPT,
};

enum SCRIPT_TYPE
{
	SCRIPT_TYPE_DIRECT,
	SCRIPT_TYPE_FROM_FILE,
};

//SM_MSG_EXECUTE_SCRIPT_RESULT
enum SST_SM_MSG_EXECUTE_SCRIPT_RESULT
{
	SST_SMESR_SERVICE_INDEX=100,
};

enum SM_MSG_EXECUTE_SCRIPT_RESULT_TYPE
{
	SMESRT_ONE_SCRIPT_IS_EXCUTING=-2,
	SMESRT_SCRIPT_FILE_NOT_EXIST=-3,
	SMESRT_SCRIPT_FILE_READ_ERROR=-4,	
};